[features]
seeds = false
[programs.localnet]
anchor_twitter = "G5fVU2wvqZzs9TmuJJEtWoGjjetnbbeGN3SL32hmK4zE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/updev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
